# DATA CLEANING DATASET MAHASISWA ITN MALANG ANGKATAN 2024

Nama  : Moh. Fauzul Adhim
NIM   : 2418046
Judul : Data Cleaning Dataset Mahasiswa ITN Malang Angkatan 2024

Dataset yang digunakan merupakan dataset mahasiswa dengan data yang
memiliki beberapa format yang tidak seragam, seperti tanggal lahir,
IPK, status beasiswa/aktif, program studi, dan nomor telepon.

CELL 1 — Upload File Excel

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Dataset_Mahasiswa_Kotor_30_Baris.xlsx to Dataset_Mahasiswa_Kotor_30_Baris (3).xlsx

CELL 2 — Import Library

In [ ]:
import pandas as pd
import re

CELL 3 — Membaca Excel

In [ ]:
# Mengambil nama file Excel yang di-upload
nama_file = list(uploaded.keys())[0]

# Membaca Excel tanpa langsung menentukan nama kolom
data_awal = pd.read_excel(nama_file, header=None)

# Menampilkan 10 baris pertama
data_awal.head(10)

,0,1,2,3,4,5,6
0,DATASET MAHASISWA ITN MALANG ANGKATAN 2024 (CO...,NaN,NaN,NaN,NaN,NaN,NaN
1,Institut Teknologi Nasional Malang - Tugas Pre...,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NIM,Nama Lengkap Mahasiswa,Program Studi & Fakultas,Tanggal Lahir,IPK Semester 1,Status Beasiswa / Aktif,No. Telepon / WA
4,2418046,Moh. Fauzul Adhim,Teknik Informatika (FTI),12-05-2005,3.75,1,0812-3456-7890
5,2418001,Andi Wijaya,Teknik Informatika - FTI,2005/08/19,"3,82",TRUE,+62 813 9988 7766
6,2418002,"Siti Nurhaliza, S.T.",Teknik Elektro (Fakultas Teknologi Industri),03/15/2006,3.4,Ya,081512345678
7,2418003,Budi S Santoso,Teknik Sipil / FTSP,14 November 2005,3.90,0,0856-1122-3344
8,2418004,Dewi Saraswati,Arsitektur (FTSP),28-02-06,2.95,FALSE,081234567811
9,2418005,Rahmat Hidayat,Teknik Mesin (FTI),10/25/2005,"3,12",Tidak,+628170099881

CELL 4 — Mencari Header Secara Otomatis

In [ ]:
# Mencari baris yang memiliki tulisan "NIM"
baris_header = None

for i in range(len(data_awal)):
    isi_baris = data_awal.iloc[i].astype(str).str.strip().tolist()

    if "NIM" in isi_baris:
        baris_header = i
        break

print("Baris header ditemukan pada baris:", baris_header)

Baris header ditemukan pada baris: 3

CELL 5 — Membuat Dataset

In [ ]:
# Membaca kembali Excel dengan header yang sudah ditemukan
df = pd.read_excel(nama_file, header=baris_header)

# Membersihkan nama kolom
df.columns = (
    df.columns
    .astype(str)
    .str.replace("\n", " ", regex=False)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

# Menampilkan nama kolom
print("Nama kolom:")
print(df.columns.tolist())

Nama kolom:
['NIM', 'Nama Lengkap Mahasiswa', 'Program Studi & Fakultas', 'Tanggal Lahir', 'IPK Semester 1', 'Status Beasiswa / Aktif', 'No. Telepon / WA']

CELL 6 — Melihat Dataset Awal

In [ ]:
print("Jumlah data:", len(df))
print("Jumlah kolom:", len(df.columns))

df.head(10)

Jumlah data: 30
Jumlah kolom: 7

,NIM,Nama Lengkap Mahasiswa,Program Studi & Fakultas,Tanggal Lahir,IPK Semester 1,Status Beasiswa / Aktif,No. Telepon / WA
0,2418046,Moh. Fauzul Adhim,Teknik Informatika (FTI),12-05-2005,3.75,1,0812-3456-7890
1,2418001,Andi Wijaya,Teknik Informatika - FTI,2005/08/19,"3,82",TRUE,+62 813 9988 7766
2,2418002,"Siti Nurhaliza, S.T.",Teknik Elektro (Fakultas Teknologi Industri),03/15/2006,3.4,Ya,081512345678
3,2418003,Budi S Santoso,Teknik Sipil / FTSP,14 November 2005,3.90,0,0856-1122-3344
4,2418004,Dewi Saraswati,Arsitektur (FTSP),28-02-06,2.95,FALSE,081234567811
5,2418005,Rahmat Hidayat,Teknik Mesin (FTI),10/25/2005,"3,12",Tidak,+628170099881
6,2418006,Siska Amalia,Teknik Kimia - FTI,01-12-2006,3.65,1,0819-8877-6655
7,2418007,Mas Rizky Pratama,Perencanaan Wilayah & Kota (PWK),17 Agustus 2004,3.20,TRUE,0813-2233-4455
8,2418008,Nabila Putri,Teknik Geodesi (FTSP),05/09/05,"3,88",Ya,0852-9900-1122
9,2418009,Dedi Kurniawan,Teknik Lingkungan / FTSP,2004-11-30,2.8,0,0812-9988-7711

CELL 7 — Mengecek Data Kosong

In [ ]:
print("Jumlah data kosong:")
print(df.isnull().sum())

Jumlah data kosong:
NIM                         0
Nama Lengkap Mahasiswa      0
Program Studi & Fakultas    0
Tanggal Lahir               0
IPK Semester 1              0
Status Beasiswa / Aktif     0
No. Telepon / WA            0
dtype: int64

CELL 8 — Mengecek Data Duplikat

In [ ]:
print("Jumlah data duplikat:", df.duplicated().sum())

Jumlah data duplikat: 0

CELL 9 — Cleaning Nama Mahasiswa

In [ ]:
df["Nama Lengkap Mahasiswa"] = (
    df["Nama Lengkap Mahasiswa"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

print("Nama mahasiswa setelah dibersihkan:")
print(df[["NIM", "Nama Lengkap Mahasiswa"]].head(10))

Nama mahasiswa setelah dibersihkan:
       NIM Nama Lengkap Mahasiswa
0  2418046      Moh. Fauzul Adhim
1  2418001            Andi Wijaya
2  2418002   Siti Nurhaliza, S.T.
3  2418003         Budi S Santoso
4  2418004         Dewi Saraswati
5  2418005         Rahmat Hidayat
6  2418006           Siska Amalia
7  2418007      Mas Rizky Pratama
8  2418008           Nabila Putri
9  2418009         Dedi Kurniawan

CELL 10 — Cleaning Program Studi

In [ ]:
df["Program Studi & Fakultas"] = (
    df["Program Studi & Fakultas"]
    .astype(str)
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

print("Program studi setelah dibersihkan:")
print(df[["NIM", "Program Studi & Fakultas"]].head(10))

Program studi setelah dibersihkan:
       NIM                      Program Studi & Fakultas
0  2418046                      Teknik Informatika (FTI)
1  2418001                      Teknik Informatika - FTI
2  2418002  Teknik Elektro (Fakultas Teknologi Industri)
3  2418003                           Teknik Sipil / FTSP
4  2418004                             Arsitektur (FTSP)
5  2418005                            Teknik Mesin (FTI)
6  2418006                            Teknik Kimia - FTI
7  2418007              Perencanaan Wilayah & Kota (PWK)
8  2418008                         Teknik Geodesi (FTSP)
9  2418009                      Teknik Lingkungan / FTSP

CELL 11 — Cleaning IPK

In [ ]:
df["IPK Semester 1"] = (
    df["IPK Semester 1"]
    .astype(str)
    .str.replace(",", ".", regex=False)
)

df["IPK Semester 1"] = pd.to_numeric(
    df["IPK Semester 1"],
    errors="coerce"
)

print("IPK setelah dibersihkan:")
print(df[["NIM", "IPK Semester 1"]].head(10))

IPK setelah dibersihkan:
       NIM  IPK Semester 1
0  2418046            3.75
1  2418001            3.82
2  2418002            3.40
3  2418003            3.90
4  2418004            2.95
5  2418005            3.12
6  2418006            3.65
7  2418007            3.20
8  2418008            3.88
9  2418009            2.80

CELL 12 — Cleaning Status

In [ ]:
def bersihkan_status(status):
    status = str(status).strip().lower()

    if status in ["1", "true", "ya"]:
        return "Ya"
    elif status in ["0", "false", "tidak"]:
        return "Tidak"
    else:
        return "Tidak diketahui"


df["Status Beasiswa / Aktif"] = (
    df["Status Beasiswa / Aktif"]
    .apply(bersihkan_status)
)

print("Status setelah dibersihkan:")
print(df[["NIM", "Status Beasiswa / Aktif"]].head(10))

Status setelah dibersihkan:
       NIM Status Beasiswa / Aktif
0  2418046                      Ya
1  2418001                      Ya
2  2418002                      Ya
3  2418003                   Tidak
4  2418004                   Tidak
5  2418005                   Tidak
6  2418006                      Ya
7  2418007                      Ya
8  2418008                      Ya
9  2418009                   Tidak

CELL 13 — Cleaning Nomor Telepon

In [ ]:
def bersihkan_telepon(no):
    no = str(no)

    # Menghapus spasi, tanda +, tanda -, dan karakter lain
    no = re.sub(r"\D", "", no)

    # Jika menggunakan kode negara 62, ubah menjadi 0
    if no.startswith("62"):
        no = "0" + no[2:]

    return no


df["No. Telepon / WA"] = (
    df["No. Telepon / WA"]
    .apply(bersihkan_telepon)
)

print("Nomor telepon setelah dibersihkan:")
print(df[["NIM", "No. Telepon / WA"]].head(10))

Nomor telepon setelah dibersihkan:
       NIM No. Telepon / WA
0  2418046     081234567890
1  2418001     081399887766
2  2418002     081512345678
3  2418003     085611223344
4  2418004     081234567811
5  2418005      08170099881
6  2418006     081988776655
7  2418007     081322334455
8  2418008     085299001122
9  2418009     081299887711

CELL 14 — Cleaning Tanggal Lahir

In [ ]:
def bersihkan_tanggal(tanggal):
    tanggal = str(tanggal).strip()

    # Format YYYY/MM/DD atau YYYY-MM-DD
    if re.match(r"^\d{4}[/\-]\d{1,2}[/\-]\d{1,2}$", tanggal):
        return pd.to_datetime(tanggal, errors="coerce")

    # Format seperti 03/15/2006 atau 08/30/06
    if "/" in tanggal:
        return pd.to_datetime(tanggal, errors="coerce", format="mixed")

    # Format seperti 12-05-2005 atau 28-02-06
    if "-" in tanggal:
        return pd.to_datetime(tanggal, errors="coerce", dayfirst=True)

    # Format tulisan seperti 14 November 2005
    return pd.to_datetime(tanggal, errors="coerce", dayfirst=True)


df["Tanggal Lahir"] = df["Tanggal Lahir"].apply(bersihkan_tanggal)

# Mengubah menjadi format YYYY-MM-DD
df["Tanggal Lahir"] = df["Tanggal Lahir"].dt.strftime("%Y-%m-%d")

print("Tanggal lahir setelah dibersihkan:")
print(df[["NIM", "Tanggal Lahir"]].head(10))

Tanggal lahir setelah dibersihkan:
       NIM Tanggal Lahir
0  2418046    2005-05-12
1  2418001    2005-08-19
2  2418002    2006-03-15
3  2418003    2005-11-14
4  2418004    2006-02-28
5  2418005    2005-10-25
6  2418006    2006-12-01
7  2418007           NaN
8  2418008    2005-05-09
9  2418009    2004-11-30

CELL 15 — Melihat Dataset Setelah Cleaning

In [ ]:
print("DATASET SETELAH DATA CLEANING")

df

DATASET SETELAH DATA CLEANING

,NIM,Nama Lengkap Mahasiswa,Program Studi & Fakultas,Tanggal Lahir,IPK Semester 1,Status Beasiswa / Aktif,No. Telepon / WA
0,2418046,Moh. Fauzul Adhim,Teknik Informatika (FTI),2005-05-12,3.75,Ya,081234567890
1,2418001,Andi Wijaya,Teknik Informatika - FTI,2005-08-19,3.82,Ya,081399887766
2,2418002,"Siti Nurhaliza, S.T.",Teknik Elektro (Fakultas Teknologi Industri),2006-03-15,3.40,Ya,081512345678
3,2418003,Budi S Santoso,Teknik Sipil / FTSP,2005-11-14,3.90,Tidak,085611223344
4,2418004,Dewi Saraswati,Arsitektur (FTSP),2006-02-28,2.95,Tidak,081234567811
5,2418005,Rahmat Hidayat,Teknik Mesin (FTI),2005-10-25,3.12,Tidak,08170099881
6,2418006,Siska Amalia,Teknik Kimia - FTI,2006-12-01,3.65,Ya,081988776655
7,2418007,Mas Rizky Pratama,Perencanaan Wilayah & Kota (PWK),NaN,3.20,Ya,081322334455
8,2418008,Nabila Putri,Teknik Geodesi (FTSP),2005-05-09,3.88,Ya,085299001122
9,2418009,Dedi Kurniawan,Teknik Lingkungan / FTSP,2004-11-30,2.80,Tidak,081299887711
10,2418010,"Eka Wahyuni, A.Md.",Bisnis Digital - FTI,2006-11-02,3.55,Tidak,081544332211
11,2418011,Pak Hendra Wijaya,Teknik Informatika (FTI),2005-06-22,3.45,Ya,081877665544
12,2418012,Maya Indah,Teknik Industri / FTI,2004-04-18,3.30,Ya,085711224455
13,2418013,Gita Gutawa,Teknik Elektro (FTI),2006-10-09,3.95,Tidak,081233445566
14,2418014,Ahmad Zaki,Teknik Sipil (FTSP),NaN,2.90,Tidak,081311112222
15,2418015,Larasati Dian,Arsitektur - FTSP,2005-12-01,3.70,Ya,085677889900
16,2418016,Bambang Sukamto,Teknik Mesin (FTI),2004-04-07,3.05,Ya,081299882211
17,2418017,Titin Sumarni,Perencanaan Wilayah dan Kota,2004-09-14,3.60,Ya,081755443322
18,2418018,Kevin Sanjaya,Teknik Geodesi - FTSP,2006-11-23,3.48,Tidak,085233441122
19,2418019,Mega Utami,Teknik Kimia (FTI),2005-05-02,3.15,Tidak,081244556677
20,2418020,Doni Kusuma,Bisnis Digital (FTI),NaN,2.75,Tidak,081388990011
21,2418021,Putri Ayu,Teknik Informatika (FTI),2006-08-30,3.80,Ya,081811223344
22,2418022,Arif Rahman,Teknik Lingkungan (FTSP),2005-07-19,3.25,Ya,085799887766
23,2418023,M. Yulia Ningsih,Teknik Sipil / FTSP,2004-03-03,3.98,Ya,081288776655
24,2418024,Hafiz Maulana,Teknik Elektro (FTI),2005-12-25,3.10,Tidak,081355667788
25,2418025,Novi Anggraini,Arsitektur (FTSP),2004-06-14,3.35,Tidak,085211223344
26,2418026,Bapak Rudi Hartono,Teknik Industri - FTI,2005-09-18,2.85,Tidak,081799001122
27,2418027,Clara Monik,Teknik Informatika (FTI),2006-01-01,3.68,Ya,081233221100
28,2418028,Fikri Haikal,Teknik Mesin (FTI),2005-11-20,3.50,Ya,081844556677
29,2418029,Siti Zubaidah,Teknik Geodesi / FTSP,2004-08-04,3.42,Tidak,085633221100

CELL 16 — Pemeriksaan Akhir

In [ ]:
print("=== HASIL PEMERIKSAAN AKHIR ===")

print("\n1. Data kosong:")
print(df.isnull().sum())

print("\n2. Data duplikat:")
print(df.duplicated().sum())

print("\n3. Tipe data:")
print(df.dtypes)

=== HASIL PEMERIKSAAN AKHIR ===

1. Data kosong:
NIM                         0
Nama Lengkap Mahasiswa      0
Program Studi & Fakultas    0
Tanggal Lahir               3
IPK Semester 1              0
Status Beasiswa / Aktif     0
No. Telepon / WA            0
dtype: int64

2. Data duplikat:
0

3. Tipe data:
NIM                           int64
Nama Lengkap Mahasiswa       object
Program Studi & Fakultas     object
Tanggal Lahir                object
IPK Semester 1              float64
Status Beasiswa / Aktif      object
No. Telepon / WA             object
dtype: object

CELL 17 — Menyimpan Dataset Bersih

In [ ]:
nama_file_bersih = "Dataset_Mahasiswa_ITN_2024_Bersih.xlsx"

df.to_excel(nama_file_bersih, index=False)

print("Dataset berhasil disimpan sebagai:")
print(nama_file_bersih)

Dataset berhasil disimpan sebagai:
Dataset_Mahasiswa_ITN_2024_Bersih.xlsx

CELL 18 — Download Dataset Bersih

In [ ]:
from google.colab import files

files.download("Dataset_Mahasiswa_ITN_2024_Bersih.xlsx")